sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tgjhuijbers/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tgjhuijbers/docker-react npm run test